'1002':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1002/FCHLLFVDSXX_L4_wHAXPI110643-78_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1002/FCHLLFVDSXX_L4_wHAXPI110643-78_2.fq.gz
'1105':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1105/FCHLLWKDSXX_L3_wHAXPI110674-75_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1105/FCHLLWKDSXX_L3_wHAXPI110674-75_2.fq.gz
'1130':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1130/FCHLLWKDSXX_L3_wHAXPI110671-80_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1130/FCHLLWKDSXX_L3_wHAXPI110671-80_2.fq.gz
'1257':
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/1257/1257.reads1.fastq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/1257/1257.reads2.fastq.gz
'1259':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1259/FCHLLWKDSXX_L2_wHAXPI110667-103_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1259/FCHLLWKDSXX_L2_wHAXPI110667-103_2.fq.gz
'1261':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1261/FCHLLWKDSXX_L2_wHAXPI110577-108_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1261/FCHLLWKDSXX_L2_wHAXPI110577-108_2.fq.gz
'1262':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1262/FCHLLWKDSXX_L2_wHAXPI110664-109_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1262/FCHLLWKDSXX_L2_wHAXPI110664-109_2.fq.gz
'1264':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1264/FCHLLWKDSXX_L2_wHAXPI110618-110_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/1264/FCHLLWKDSXX_L2_wHAXPI110618-110_2.fq.gz
'2418':
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/2418/2418.reads1.fastq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/2418/2418.reads2.fastq.gz
'2541':
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/2541/2541.reads1.fastq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/2541/2541.reads2.fastq.gz
'2660':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/2660/FCHLLWKDSXX_L2_wHAXPI110720-81_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/2660/FCHLLWKDSXX_L2_wHAXPI110720-81_2.fq.gz
'3223':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/3223/FCHLLWKDSXX_L2_wHAXPI110714-82_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/3223/FCHLLWKDSXX_L2_wHAXPI110714-82_2.fq.gz
'3224':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/3224/FCHLLWKDSXX_L2_wHAXPI110579-83_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/3224/FCHLLWKDSXX_L2_wHAXPI110579-83_2.fq.gz
'3809':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/3809/FCHLLWKDSXX_L2_wHAXPI110719-96_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/3809/FCHLLWKDSXX_L2_wHAXPI110719-96_2.fq.gz
'4466':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/4466/FCHLLWKDSXX_L2_wHAXPI110722-95_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/4466/FCHLLWKDSXX_L2_wHAXPI110722-95_2.fq.gz
'5221':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5221/FCHLLWKDSXX_L2_wHAXPI110608-84_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5221/FCHLLWKDSXX_L2_wHAXPI110608-84_2.fq.gz
'5222':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5222/FCHLLWKDSXX_L2_wHAXPI110681-85_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5222/FCHLLWKDSXX_L2_wHAXPI110681-85_2.fq.gz
'5706':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5706/FCHLLWKDSXX_L2_wHAXPI110631-88_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5706/FCHLLWKDSXX_L2_wHAXPI110631-88_2.fq.gz
'5707':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5707/FCHLLWKDSXX_L2_wHAXPI110641-89_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5707/FCHLLWKDSXX_L2_wHAXPI110641-89_2.fq.gz
'5708':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5708/FCHLLWKDSXX_L2_wHAXPI110694-90_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5708/FCHLLWKDSXX_L2_wHAXPI110694-90_2.fq.gz
'5709':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5709/FCHLLWKDSXX_L2_wHAXPI110673-92_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5709/FCHLLWKDSXX_L2_wHAXPI110673-92_2.fq.gz
'5710':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5710/FCHLLWKDSXX_L2_wHAXPI110712-93_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/5710/FCHLLWKDSXX_L2_wHAXPI110712-93_2.fq.gz
'579':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/579/FCHLLWKDSXX_L2_wHAXPI110640-100_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/579/FCHLLWKDSXX_L2_wHAXPI110640-100_2.fq.gz
'580':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/580/FCHLLWKDSXX_L2_wHAXPI110693-101_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/580/FCHLLWKDSXX_L2_wHAXPI110693-101_2.fq.gz
'581':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/581/FCHLLWKDSXX_L2_wHAXPI110578-102_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/581/FCHLLWKDSXX_L2_wHAXPI110578-102_2.fq.gz
'6272':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6272/FCHLLWKDSXX_L3_wHAXPI110613-40_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6272/FCHLLWKDSXX_L3_wHAXPI110613-40_2.fq.gz
'6273':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6273/FCHLLWKDSXX_L3_wHAXPI110567-51_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6273/FCHLLWKDSXX_L3_wHAXPI110567-51_2.fq.gz
'6274':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6274/FCHLLWKDSXX_L3_wHAXPI110588-41_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6274/FCHLLWKDSXX_L3_wHAXPI110588-41_2.fq.gz
'6280':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6280/FCHLLWKDSXX_L3_wHAXPI110603-52_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6280/FCHLLWKDSXX_L3_wHAXPI110603-52_2.fq.gz
'6436':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6436/FCHLLWKDSXX_L3_wHAXPI110582-36_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/6436/FCHLLWKDSXX_L3_wHAXPI110582-36_2.fq.gz
'7144':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7144/FCHLLWKDSXX_L3_wHAXPI110596-54_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7144/FCHLLWKDSXX_L3_wHAXPI110596-54_2.fq.gz
'7146':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7146/FCHLLWKDSXX_L3_wHAXPI110715-53_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7146/FCHLLWKDSXX_L3_wHAXPI110715-53_2.fq.gz
'7147':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7147/FCHLLWKDSXX_L3_wHAXPI110707-30_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7147/FCHLLWKDSXX_L3_wHAXPI110707-30_2.fq.gz
'7151':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7151/FCHLLWKDSXX_L3_wHAXPI110703-33_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7151/FCHLLWKDSXX_L3_wHAXPI110703-33_2.fq.gz
'7152':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7152/FCHLLWKDSXX_L3_wHAXPI110691-34_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7152/FCHLLWKDSXX_L3_wHAXPI110691-34_2.fq.gz
'7155':
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/7155/7155.reads1.fastq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/7155/7155.reads2.fastq.gz
'7156':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7156/FCHLLWKDSXX_L3_wHAXPI110695-45_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7156/FCHLLWKDSXX_L3_wHAXPI110695-45_2.fq.gz
'7160':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7160/FCHLLWKDSXX_L3_wHAXPI110635-56_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7160/FCHLLWKDSXX_L3_wHAXPI110635-56_2.fq.gz
'7161':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7161/FCHLLWKDSXX_L3_wHAXPI110665-57_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7161/FCHLLWKDSXX_L3_wHAXPI110665-57_2.fq.gz
'7162':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7162/FCHLLWKDSXX_L3_wHAXPI110633-58_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7162/FCHLLWKDSXX_L3_wHAXPI110633-58_2.fq.gz
'7163':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7163/FCHLLWKDSXX_L3_wHAXPI110668-46_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7163/FCHLLWKDSXX_L3_wHAXPI110668-46_2.fq.gz
'7966':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7966/FCHLLWKDSXX_L3_wHAXPI110619-76_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/7966/FCHLLWKDSXX_L3_wHAXPI110619-76_2.fq.gz
'8622':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8622/FCHLLWKDSXX_L3_wHAXPI110595-63_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8622/FCHLLWKDSXX_L3_wHAXPI110595-63_2.fq.gz
'8623':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8623/FCHLLWKDSXX_L3_wHAXPI110682-66_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8623/FCHLLWKDSXX_L3_wHAXPI110682-66_2.fq.gz
'8627':
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/8627/8627.reads1.fastq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/8627/8627.reads2.fastq.gz
'8628':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8628/FCHLLWKDSXX_L2_wHAXPI110561-94_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8628/FCHLLWKDSXX_L2_wHAXPI110561-94_2.fq.gz
'8922':
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/8922/8922.reads1.fastq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/29samples/clean/8922/8922.reads2.fastq.gz
'8928':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8928/FCHLLWKDSXX_L3_wHAXPI110718-74_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8928/FCHLLWKDSXX_L3_wHAXPI110718-74_2.fq.gz
'8929':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8929/FCHLLWKDSXX_L3_wHAXPI110622-62_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8929/FCHLLWKDSXX_L3_wHAXPI110622-62_2.fq.gz
'8931':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8931/FCHLLWKDSXX_L3_wHAXPI110689-73_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8931/FCHLLWKDSXX_L3_wHAXPI110689-73_2.fq.gz
'8932':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8932/FCHLLWKDSXX_L3_wHAXPI110677-61_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8932/FCHLLWKDSXX_L3_wHAXPI110677-61_2.fq.gz
'8943':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8943/FCHLLWKDSXX_L3_wHAXPI110655-68_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8943/FCHLLWKDSXX_L3_wHAXPI110655-68_2.fq.gz
'8950':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8950/FCHLLWKDSXX_L3_wHAXPI110612-70_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/8950/FCHLLWKDSXX_L3_wHAXPI110612-70_2.fq.gz
'9124':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/9124/FCHLLWKDSXX_L3_wHAXPI110623-60_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/9124/FCHLLWKDSXX_L3_wHAXPI110623-60_2.fq.gz
'931':
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/931/FCHLLFVDSXX_L4_wHAXPI110660-77_1.fq.gz
- /steveData/africaFQ2019/University_of_Copenhagen_data/79samplse/Clean/931/FCHLLFVDSXX_L4_wHAXPI110660-77_2.fq.gz
